export default {
  login: 'SvetlanaStoycheva',
  id: 58769975,
  node_id: 'MDQ6VXNlcjU4NzY5OTc1',
  avatar_url: 'https://avatars.githubusercontent.com/u/58769975?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/SvetlanaStoycheva',
  html_url: 'https://github.com/SvetlanaStoycheva',
  followers_url: 'https://api.github.com/users/SvetlanaStoycheva/followers',
  following_url:
    'https://api.github.com/users/SvetlanaStoycheva/following{/other_user}',
  gists_url: 'https://api.github.com/users/SvetlanaStoycheva/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/SvetlanaStoycheva/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/SvetlanaStoycheva/subscriptions',
  organizations_url: 'https://api.github.com/users/SvetlanaStoycheva/orgs',
  repos_url: 'https://api.github.com/users/SvetlanaStoycheva/repos',
  events_url: 'https://api.github.com/users/SvetlanaStoycheva/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/SvetlanaStoycheva/received_events',
  type: 'User',
  site_admin: false,
  name: 'Svetlana Stoycheva',
  company: null,
  blog: '',
  location: 'Sofia',
  email: null,
  hireable: true,
  bio: 'JavaScript, CSS, HTML, React Bulgarian, English, German',
  twitter_username: null,
  public_repos: 16,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2019-12-11T09:30:08Z',
  updated_at: '2021-04-02T14:28:44Z',
}
